### PR TITLE
screen sharing function added

### PR DESCRIPTION
**Pull request by choco9620**
hello, in this pull request I add the screen sharing functionality

### CODE REVIEW

**Comment by fifinfield** [comment]
@choco9620 I tried your pull request to share screen. I have a query.
When i share my screen it shows up in the small thumbnail. For a screen share i feel it should be published to the main screen instead. Have you tried it? Can you let me know how i could do that?

**Comment by choco9620** [comment]
> @ choco9620 Probé tu solicitud de extracción para compartir la pantalla. Tengo una consulta.
> Cuando comparto mi pantalla, aparece en la miniatura pequeña. Para compartir una pantalla, creo que debería publicarse en la pantalla principal. ¿Lo has probado? ¿Puedes decirme cómo puedo hacer eso?

Hello Fifinfield, what I did for this was to exchange the screen size style of the main one with the thumbnail and so the shared one remains main, it also adds a function that when clicking on a thumbnail is placed in main, if you want to see code me you say and I show you what I did...

**Comment by fifinfield** [comment]
@choco9620 Thanks for your response. It will be great if you can show me how to switch share screen to main and thumbnail click to main.

**Comment by fifinfield** [comment]
> > @ choco9620 Probé tu solicitud de extracción para compartir la pantalla. Tengo una consulta.
> > Cuando comparto mi pantalla, aparece en la miniatura pequeña. Para compartir una pantalla, creo que debería publicarse en la pantalla principal. ¿Lo has probado? ¿Puedes decirme cómo puedo hacer eso?
> 
> Hello Fifinfield, what I did for this was to exchange the screen size style of the main one with the thumbnail and so the shared one remains main, it also adds a function that when clicking on a thumbnail is placed in main, if you want to see code me you say and I show you what I did...

@choco9620 Waiting for your reply. Thank you.

**Comment by ravola** [comment]
> > @ choco9620 Probé tu solicitud de extracción para compartir la pantalla. Tengo una consulta.
> > Cuando comparto mi pantalla, aparece en la miniatura pequeña. Para compartir una pantalla, creo que debería publicarse en la pantalla principal. ¿Lo has probado? ¿Puedes decirme cómo puedo hacer eso?
> 
> Hello Fifinfield, what I did for this was to exchange the screen size style of the main one with the thumbnail and so the shared one remains main, it also adds a function that when clicking on a thumbnail is placed in main, if you want to see code me you say and I show you what I did...

@choco9620 hi waiting for response

**Comment by fifinfield** [comment]
@choco9620 Waiting for your help.

**Comment by choco9620** [comment]
hi fifinfield, this is my code for sharing, 

1. create new vars for sharing 

`this.shareClient = {};
this.shareStream = {};`

2. create methon init sharing

`streamInitSharing = (uid, attendeeMode, videoProfile, config) => {
    let defaultConfig = {
      streamID: uid,
      audio: false,
      video: false,
      screen: true,
    };

    switch (attendeeMode) {
      case "audio-only":
        defaultConfig.video = false;
        break;
      case "audience":
        defaultConfig.video = false;
        defaultConfig.audio = false;
        break;
      default:
      case "video":
        break;
    }

    let stream = AgoraRTC.createStream(merge(defaultConfig, config));
    stream.setScreenProfile("720p_1");
    return stream;
  };`

3. add method click function, sharing

`  sharing = (e) => {
    if (this.state.stateSharing) {
      this.shareClient && this.shareClient.unpublish(this.shareStream);
      this.shareStream && this.shareStream.close();
      this.state.stateSharing = false;
    } else {
      this.state.stateSharing = true;
      let $ = this.props;
      // init AgoraRTC local client
      this.shareClient = AgoraRTC.createClient({ mode: $.transcode });
      this.shareClient.init($.appId, () => {
        //console.log("AgoraRTC client initialized");
        this.shareClient.join($.appId, $.channel, undefined, (uid) => {
          //this.state.uid = uid;
          //console.log("User " + uid + " join channel successfully");
          //console.log("At " + new Date().toLocaleTimeString());
          // create local stream
          // It is not recommended to setState in function addStream
          this.shareStream = this.streamInitSharing(
            uid,
            $.attendeeMode,
            $.videoProfile
          );
          this.shareStream.init(
            () => {
              if ($.attendeeMode !== "audience") {
                this.shareStream.params.nameUser = "Pantalla";
                this.addStream(this.shareStream, true);
                this.shareClient.publish(this.shareStream, (err) => {
                  //console.log("Publish local stream error: " + err);
                });
              }
              this.setState({ readyState: true });
            },
            (err) => {
              //console.log("getUserMedia failed", err);
              this.setState({ readyState: true });
            }
          );
        });
      });
    }
  };`


that's all, I hope it helps you, please write me your email to send you the complete file.

**Comment by fifinfield** [comment]
@choco9620 thank you. I will try this code. This is my email address plutonicdiorite@gmail.com 
Also you mentioned about click on thumbnail to place in main. Please send code to email address. Thank you 👍

**Comment by AjithGoku** [comment]
> hi @fifinfield, this is my code for sharing,
> 
> 1. create new vars for sharing
> 
> `this.shareClient = {}; this.shareStream = {};`
> 
> 1. create methon init sharing
> 
> streamInitSharing = (uid, attendeeMode, videoProfile, config) => {
> let defaultConfig = {
> streamID: uid,
> audio: false,
> video: false,
> screen: true,
> };
> 
> ```
> switch (attendeeMode) {
>   case "audio-only":
>     defaultConfig.video = false;
>     break;
>   case "audience":
>     defaultConfig.video = false;
>     defaultConfig.audio = false;
>     break;
>   default:
>   case "video":
>     break;
> }
> 
> let stream = AgoraRTC.createStream(merge(defaultConfig, config));
> stream.setScreenProfile("720p_1");
> return stream;
> ```
> 
> };
> 
> 1. add method click function, sharing
> 
> sharing = (e) => {
> if (this.state.stateSharing) {
> this.shareClient && this.shareClient.unpublish(this.shareStream);
> this.shareStream && this.shareStream.close();
> this.state.stateSharing = false;
> } else {
> this.state.stateSharing = true;
> let $ = this.props;
> // init AgoraRTC local client
> this.shareClient = AgoraRTC.createClient({ mode: $.transcode });
> this.shareClient.init($.appId, () => {
> console.log("AgoraRTC client initialized");
> this.shareClient.join($.appId, $.channel, undefined, (uid) => {
> console.log("User " + uid + " join channel successfully");
> console.log("At " + new Date().toLocaleTimeString());
> this.shareStream = this.streamInitSharing(
> uid,
> $.attendeeMode,
> $.videoProfile
> );
> this.shareStream.init(
> () => {
> if ($.attendeeMode !== "audience") {
> this.shareStream.params.nameUser = "Pantalla";
> this.addStream(this.shareStream, true);
> this.shareClient.publish(this.shareStream, (err) => {
> console.log("Publish local stream error: " + err);
> });
> }
> this.setState({ readyState: true });
> },
> (err) => {
> console.log("getUserMedia failed", err);
> this.setState({ readyState: true });
> }
> );
> });
> });
> }
> }
> 
> that's all, I hope it helps you, please write me your email to send you the complete file.

Thank u. Can u share the click on thumbnail to place in the main to this email address ajithgoku333@gmail.com

**Comment by fifinfield** [comment]
@choco9620 i have shared my email address. Can you also share details of thumbnail to main screen. How you did that.

**Comment by fifinfield** [comment]
@choco9620 any luck sharing the  function that when clicking on a thumbnail is placed in main

**Pull request merged**
